### PR TITLE
Add triangle draw function

### PR DESCRIPTION
**Pull request by Falke-Design**

### CODE REVIEW

**Comment by codeofsumit** [comment]
Thanks for your work on this feature 🙏! Please update with the current `develop` branch.
I'm skeptical if we really should bundle so much Turf funtions. The library is getting too big 🤔. I will check out the feature though 👍

**Comment by Falke-Design** [comment]
Hi I have a lot of struggles with Github. I have created a new Fork with a Triangle Branch now. Can i create a Pull Request to this PR or do I need to create a new PR? And how I update my branch with your develop branch? With the Compare function?

I had forgot to uninstall the Turf libraries but they are not longer in the code used. I had created own functions.

**Comment by codeofsumit** [comment]
😅 no worries. So you can do a pull request from any branch into any other branch. This Pull request is from your feature branch into my develop branch.
You can either commit changes directly into your feature branch (this PR is then updated).
You can also update your feature branch from my develop branch. This will create a merge conflict in the `package-lock.json` that you have to resolve and commit. 

But it also looks like you have deleted this branch? If so, you can close this PR and recreate a pull request from your new branch.

**Comment by Falke-Design** [comment]
New PR creaeted

**Pull request closed without merging**
