### PR TITLE
Added fixes to various modules to account for preferCanvas being set …

### PR DESCRIPTION
**Pull request by chriswilley**
…to true on a Leaflet map. See issues #268 and #269

### CODE REVIEW

**Comment by codeofsumit** [comment]
@chriswilley thanks a ton for your work on this. I forked this and made a few minor adjustments.
Could you check if this branch is working for you?
https://github.com/codeofsumit/leaflet.pm/pull/286

Huge thanks for the preferCanvas demos! Helps a lot!

**Comment by chriswilley** [comment]
No problem! Which branch did you commit your changes to? I don't see a branch called pr/270, and both develop and prefer_canvas_true are showing as current on my end.

**Comment by chriswilley** [comment]
For some reason I couldn't see the pr/270 branch no matter what I did, so I re-cloned the repo to another location and then I could see it. Weird. Anyway, everything looks good!

**Comment by codeofsumit** [comment]
@chriswilley this is the branch
https://github.com/codeofsumit/leaflet.pm/tree/pr/270
cool will merge, thanks for checking

**Pull request closed without merging**
