### PR TITLE
(Basic) Remove last vertex support

### LINKED ISSUE #267: Remove last vertex
How can one remove the last added vertex? 
Is there a key -function for it, just like the ALT-key when snapping?

### PR DESCRIPTION
**Pull request by cosme-benito**
This PR adds a method to remove the last vertex. This method only works while you are in "drawing" mode, not edit mode. Since Markers immediately finish the shape, this feature doesn't work for points either. 

Usage

```javascript
this.map.pm.removeLastVertex('Line');
```

Fixes #267, credit to @sasfeat since this solution is based on his snippet.

### CODE REVIEW

**Comment by cosme-benito** [comment]
Local ```npm run test``` seems to work, any tips what I could possible be doing wrong?

**Comment by codeofsumit** [comment]
@cosme-benito seems like the build failed on Travis-CI. I restarted the test, works now.

**Comment by m0t0r** [comment]
Hi, @codeofsumit, @cosme-benito any updates on this PR? This feature is really needed. Thank you

**Comment by codeofsumit** [comment]
this is now implemented.

You can click it via the action button, or programatically trigger it with `map.pm.Draw.Line._removeLastVertex();` or `map.pm.Draw.Poly._removeLastVertex();` repsectively.

**Pull request closed without merging**
