### PR TITLE
Union/Merge layers and Norwegian translation

### PR DESCRIPTION
**Pull request by hefler**
I've been running my own fork of `leaflet.pm`, in that I've added union/merge layers and Norwegian translation. I had earlier done a translation to Portuguese, which I've noticed now that Brazilian Portuguese has been added too. Since I don't have much time do any cleanup/tests/etc. I let that into your hands. :)

I've also add a `dist` folder which is useful for my case (as I my script is minified and bundled up together with others).

### CODE REVIEW

**Comment by hefler** [comment]
Oh! Just merged @lobovmaxim's PR's (#366) into mine fork, so just be aware of that too 😅

**Comment by codeofsumit** [comment]
@hefler please separate PRs of features and language additions.
This PR also has some things that need changing before I can merge it but before I review them, please create separate PRs for "Merge layers" and for "Norwegian Language"

**Comment by hefler** [comment]
Yeah, it was more for inspiration, I don't have much time to do the "cleanup".

**Comment by codeofsumit** [comment]
got it, thanks @hefler 🎉

**Pull request closed without merging**
